alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists default_whatsapp_e164 text check(default_whatsapp_e164 is null or default_whatsapp_e164 ~ '^[1-9][0-9]{7,14}$');
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.birthday_pages add column if not exists suspended_at timestamptz;
alter table public.birthday_pages drop constraint if exists birthday_pages_status_check;
alter table public.birthday_pages add constraint birthday_pages_status_check check(status in('draft','published','archived','suspended'));
create table public.wish_rate_limits(id bigint generated always as identity primary key,page_id uuid not null references public.birthday_pages(id) on delete cascade,network_hash text not null,created_at timestamptz not null default now());
create index wish_rate_limits_page_network_created_idx on public.wish_rate_limits(page_id,network_hash,created_at desc);
alter table public.wish_rate_limits enable row level security;revoke all on public.wish_rate_limits from anon,authenticated;
update storage.buckets set public=false where id in('birthday-media','wishlist-media');
drop policy if exists "birthday_media_public_read" on storage.objects;drop policy if exists "wishlist_media_public_read" on storage.objects;
create policy "birthday_media_owner_read" on storage.objects for select to authenticated using(bucket_id='birthday-media' and owner_id=(select auth.uid()::text));
create policy "wishlist_media_owner_read" on storage.objects for select to authenticated using(bucket_id='wishlist-media' and owner_id=(select auth.uid()::text));
create policy "wishlist_media_owner_manage" on storage.objects for update to authenticated using(bucket_id='wishlist-media' and owner_id=(select auth.uid()::text)) with check(bucket_id='wishlist-media' and owner_id=(select auth.uid()::text));
create policy "wishlist_media_owner_delete" on storage.objects for delete to authenticated using(bucket_id='wishlist-media' and owner_id=(select auth.uid()::text));
create or replace function private.is_admin(user_uuid uuid) returns boolean language sql security definer set search_path='' as $$select exists(select 1 from public.user_roles where user_id=user_uuid and role='admin');$$;
revoke execute on function private.is_admin(uuid) from public,anon,authenticated;
create policy "manual_payment_admin_read" on public.manual_payment_submissions for select to authenticated using((select private.is_admin((select auth.uid()))));
create policy "audit_admin_read" on public.admin_audit_logs for select to authenticated using((select private.is_admin((select auth.uid()))));
create policy "roles_own_read" on public.user_roles for select to authenticated using(user_id=(select auth.uid()));
create or replace function private.enforce_free_page_limit() returns trigger language plpgsql security definer set search_path='' as $$declare is_pro boolean;begin select exists(select 1 from public.account_entitlements e where e.user_id=new.owner_id and e.plan='pro') into is_pro;if not is_pro and (select count(*) from public.birthday_pages p where p.owner_id=new.owner_id and p.status<>'archived')>=1 then raise exception 'Free accounts can create one Birthday Page';end if;return new;end;$$;
revoke execute on function private.enforce_free_page_limit() from public,anon,authenticated;create trigger enforce_page_plan_limit before insert on public.birthday_pages for each row execute function private.enforce_free_page_limit();
create or replace function private.enforce_photo_limit() returns trigger language plpgsql security definer set search_path='' as $$declare owner uuid;is_pro boolean;max_count integer;begin select owner_id into owner from public.birthday_pages where id=new.page_id;select exists(select 1 from public.account_entitlements where user_id=owner and plan='pro') into is_pro;max_count:=case when is_pro then 15 else 5 end;if (select count(*) from public.page_photos where page_id=new.page_id)>=max_count then raise exception 'Photo limit reached';end if;return new;end;$$;
revoke execute on function private.enforce_photo_limit() from public,anon,authenticated;create trigger enforce_photo_plan_limit before insert on public.page_photos for each row execute function private.enforce_photo_limit();
create or replace function private.enforce_wishlist_limit() returns trigger language plpgsql security definer set search_path='' as $$declare owner uuid;is_pro boolean;begin select owner_id into owner from public.birthday_pages where id=new.page_id;select exists(select 1 from public.account_entitlements where user_id=owner and plan='pro') into is_pro;if not is_pro and (select count(*) from public.birthday_wishlist_items where page_id=new.page_id)>=5 then raise exception 'Wishlist limit reached';end if;return new;end;$$;
revoke execute on function private.enforce_wishlist_limit() from public,anon,authenticated;create trigger enforce_wishlist_plan_limit before insert on public.birthday_wishlist_items for each row execute function private.enforce_wishlist_limit();
